// index.ts — main process entry point
// Creates the main panel window, the floating companion window,
// system tray, and registers all IPC handlers.
//
// Lifecycle:
//   - Closing the main window QUITS the app (no hidden background processes)
//   - Companion window closes with the main window
//   - All speech and analysis stop on quit
//   - Tray provides Open/Quit shortcuts but the app does NOT hide to tray by default

import { app, BrowserWindow, Tray, Menu, nativeImage, shell } from 'electron'
import { join } from 'path'
import { IPC } from '../renderer/src/types'
import { registerIpcHandlers } from './ipc-handlers'
import { createCompanionWindow, showCompanion, hideCompanion, resetCompanionPosition } from './companion-window'
import { createGuidanceWindow, destroyGuidanceWindow, showLastGuidance } from './guidance-window'
import { stopAnalysisLoop } from './analysis-loop'
import { initProjects } from './projects'
import { createVoicePlayerWindow, destroyVoicePlayer } from './voice-player'
import { migratePlaintextSecrets } from './secure-store'
import { settingsFilePath, loadRedactedSettings } from './memory'
import { isModelConfigured } from '../renderer/src/types'
import { debugLog } from './debug-log'
import { isSafeExternalUrl, isAllowedAppNavigation, isBlockedDevShortcut } from './navigation-guard'
import { registerE2eTestHooks } from './e2e-hooks'

// ─── Global web-contents security guard ──────────────────────────────────────
// Applies to EVERY renderer (main, companion, guidance, voice — and anything
// else that might ever be created), not just windows that remembered to set
// their own handlers:
//   - window.open is always denied; https/mailto are forwarded to the OS
//     browser via shell.openExternal, everything else is dropped.
//   - will-navigate / will-redirect may only target the app's own renderer
//     (the packaged file:// bundle, or the dev server during `npm run dev`).
//   - In packaged builds, reload/devtools shortcuts (Ctrl+R, F5, Ctrl+Shift+I)
//     are blocked at the input level.
app.on('web-contents-created', (_event, contents) => {
  contents.setWindowOpenHandler(({ url }) => {
    // Only forward https: / mailto: to the OS browser. Deny file:, custom
    // protocols, and malformed URLs (which could trigger unsafe handlers).
    if (isSafeExternalUrl(url)) {
      shell.openExternal(url)
    } else {
      debugLog('[Security] blocked openExternal for disallowed URL protocol')
    }
    return { action: 'deny' }
  })

  const guardNavigation = (event: Electron.Event, url: string): void => {
    if (!isAllowedAppNavigation(url, process.env['ELECTRON_RENDERER_URL'])) {
      event.preventDefault()
      console.warn('[Security] blocked navigation to a non-app URL')
    }
  }
  contents.on('will-navigate', guardNavigation)
  contents.on('will-redirect', guardNavigation)

  if (app.isPackaged) {
    contents.on('before-input-event', (event, input) => {
      if (isBlockedDevShortcut(input)) event.preventDefault()
    })
  }
})

// ─── Application menu ────────────────────────────────────────────────────────
// The stock Electron menu exposes Reload and Toggle Developer Tools — remove it.
// Windows/Linux: no menu at all. macOS: minimal app + Edit menu only (Edit keeps
// the standard clipboard shortcuts working).
function installAppMenu(): void {
  if (process.platform === 'darwin') {
    Menu.setApplicationMenu(Menu.buildFromTemplate([
      { role: 'appMenu' },
      { role: 'editMenu' },
    ]))
  } else {
    Menu.setApplicationMenu(null)
  }
}

let mainWindow: BrowserWindow | null = null
let companionWindow: BrowserWindow | null = null
let guidanceWindow: BrowserWindow | null = null
let voicePlayerWindow: BrowserWindow | null = null
let tray: Tray | null = null

// App / tray icon — the square Buildy badge (build/icon.png, generated by
// scripts/make-app-icon.js from the logo). Packaged builds ship it via
// electron-builder extraResources as resources/icon.png (src/ is NOT inside
// app.asar — build.files is out/ + package.json only), so it must be resolved
// through process.resourcesPath there. Dev runs read it from the repo.
const LOGO_PATH = app.isPackaged
  ? join(process.resourcesPath, 'icon.png')
  : join(__dirname, '../../build/icon.png')

// ─── Shutdown ────────────────────────────────────────────────────────────────

/**
 * Clean shutdown: stop analysis, stop speech, close all windows, quit.
 * Called from every exit path to guarantee no orphaned processes.
 */
function shutdownApp(): void {
  ;(app as any).isQuitting = true

  // 1. Stop the background analysis loop
  stopAnalysisLoop()

  // 2. Tell the companion renderer to stop TTS immediately
  if (companionWindow && !companionWindow.isDestroyed()) {
    try {
      companionWindow.webContents.send(IPC.COMPANION_SHUTDOWN)
    } catch {
      // Window may already be gone
    }
  }

  // 3. Destroy companion + guidance windows
  if (companionWindow && !companionWindow.isDestroyed()) {
    companionWindow.destroy()
  }
  companionWindow = null

  destroyGuidanceWindow()
  guidanceWindow = null

  destroyVoicePlayer()
  voicePlayerWindow = null

  // 4. Destroy main window (allow it to close for real)
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.destroy()
  }
  mainWindow = null

  // 5. Destroy tray
  if (tray && !tray.isDestroyed()) {
    tray.destroy()
  }
  tray = null

  // 6. Quit the process
  app.quit()
}

// ─── Main panel window (hidden by default — companion is primary UI) ─────────

function createMainWindow(): BrowserWindow {
  const window = new BrowserWindow({
    width: 520,
    height: 720,
    minWidth: 480,
    minHeight: 600,
    title: 'Buildy Settings',
    icon: LOGO_PATH,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
    backgroundColor: '#1C1C1E',
    show: false,
  })

  if (process.env['ELECTRON_RENDERER_URL']) {
    window.loadURL(process.env['ELECTRON_RENDERER_URL'])
    // DevTools ONLY in a debug dev run — never in packaged builds.
    if (process.env['BUILDY_DEBUG'] && !app.isPackaged) {
      window.webContents.openDevTools({ mode: 'detach' })
    }
  } else {
    window.loadFile(join(__dirname, '../renderer/index.html'))
  }

  // Panel stays hidden on launch — companion is the primary UI.
  // User opens it from companion gear icon or system tray.
  // window.open / navigation are covered by the global web-contents guard above.

  // Closing the panel just hides it — companion keeps running.
  // Quitting the app is done via tray or closing the companion.
  window.on('close', (e) => {
    if (!(app as any).isQuitting) {
      e.preventDefault()
      window.hide()
    }
  })

  return window
}

// ─── System Tray ─────────────────────────────────────────────────────────────

function createSystemTray(): Tray {
  // Tray icon from the Buildy logo, scaled down to a tray-appropriate size.
  // Falls back to an empty image if the file can't be loaded.
  const loadedIcon = nativeImage.createFromPath(LOGO_PATH)
  const trayIcon = loadedIcon.isEmpty()
    ? nativeImage.createEmpty()
    : loadedIcon.resize({ width: 18, height: 18 })
  const newTray = new Tray(trayIcon)

  // Read-only tray health for the e2e suite (booleans only — no capability is
  // exposed, so this is safe to leave in packaged builds; the packaged e2e run
  // asserts the icon file actually loaded from resources/).
  ;(globalThis as Record<string, unknown>)['__buildyTrayHealth'] = {
    created: !newTray.isDestroyed(),
    iconLoaded: !loadedIcon.isEmpty(),
  }

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Show Buildy',
      click: () => {
        // showCompanion() re-asserts the screen-saver always-on-top level.
        showCompanion()
      },
    },
    {
      label: 'Hide Buildy',
      click: () => {
        hideCompanion()
      },
    },
    {
      label: 'Show last guidance',
      click: () => {
        showLastGuidance()
      },
    },
    {
      label: 'Reset Position',
      click: () => {
        resetCompanionPosition()
      },
    },
    {
      label: 'Settings',
      click: () => {
        mainWindow?.show()
        mainWindow?.focus()
      },
    },
    { type: 'separator' },
    {
      label: 'Quit Buildy',
      click: () => {
        shutdownApp()
      },
    },
  ])

  newTray.setToolTip('Buildy — your builder buddy')
  newTray.setContextMenu(contextMenu)

  newTray.on('double-click', () => {
    showCompanion()
  })

  return newTray
}

// ─── App lifecycle ────────────────────────────────────────────────────────────

// Track quit intent so panel close handler knows to actually close
;(app as any).isQuitting = false

// Single-instance lock: if a second launch happens (e.g. user clicks the taskbar
// icon / re-runs the app), Electron fires 'second-instance' on the FIRST instance
// instead of starting a new one. We use that to re-summon the companion.
const gotInstanceLock = app.requestSingleInstanceLock()
if (!gotInstanceLock) {
  app.quit()
} else {
  app.on('second-instance', () => {
    console.log('[App] second-instance — summoning companion')
    showCompanion()
  })
}

app.whenReady().then(async () => {
  if (!gotInstanceLock) return  // second instance is quitting — don't create windows

  // No stock menu (it exposes Reload / Toggle Developer Tools).
  installAppMenu()

  // One-time: move any plaintext API keys out of settings.json into encrypted storage.
  try { migratePlaintextSecrets(settingsFilePath) } catch (e) { console.error('[SecureStore] migration failed:', e) }

  // Project-scoped memory: run the one-time legacy migration (idempotent, never
  // deletes data) and activate the persisted active project BEFORE any window
  // can read memory. Also initialises the Nemp layer for that project.
  // Non-fatal if it can't load.
  await initProjects().catch((e) => console.error('[Projects] init failed:', e))

  mainWindow = createMainWindow()
  companionWindow = createCompanionWindow()
  guidanceWindow = createGuidanceWindow(companionWindow)
  voicePlayerWindow = createVoicePlayerWindow()
  tray = createSystemTray()

  // Register IPC handlers ONCE, with getters so they always target the current
  // window even if a window is recreated (see app.on('activate')).
  registerIpcHandlers(() => mainWindow!, () => companionWindow)

  // e2e-only fixture hooks (no-op unless BUILDY_E2E=1 and not packaged).
  registerE2eTestHooks()

  // First launch (or unconfigured install): there is NO default model, so open
  // the Settings panel automatically. The mascot label says
  // "Set me up: click the gear" until a provider key + model are chosen.
  try {
    const redacted = await loadRedactedSettings()
    if (!isModelConfigured(redacted)) {
      mainWindow.once('ready-to-show', () => { mainWindow?.show(); mainWindow?.focus() })
      // ready-to-show may already have fired for a fast-loading window:
      if (mainWindow.webContents.isLoading() === false) { mainWindow.show(); mainWindow.focus() }
    }
  } catch (e) {
    console.warn('[App] first-launch settings check failed:', e)
  }

  console.log('Buildy launched — companion only (panel hidden unless setup is needed)')

  // ─── Dev-only: companion idle-CPU measurement (Phase 6, target < 3%) ───────
  // Logs the companion renderer process's CPU every 5s via app.getAppMetrics().
  // percentCPUUsage is measured since the PREVIOUS getAppMetrics() call, so the
  // first sample is a warm-up and is skipped. Not compiled out, but fully
  // gated on !app.isPackaged so packaged builds never run it.
  if (!app.isPackaged) {
    let warmedUp = false
    const cpuTimer = setInterval(() => {
      if (!companionWindow || companionWindow.isDestroyed()) return
      const pid = companionWindow.webContents.getOSProcessId()
      const metric = app.getAppMetrics().find((m) => m.pid === pid)
      if (!metric) return
      if (!warmedUp) { warmedUp = true; return }
      console.log(`[MascotCPU] companion renderer pid=${pid} cpu=${metric.cpu.percentCPUUsage.toFixed(2)}%`)
    }, 5000)
    app.on('before-quit', () => clearInterval(cpuTimer))
  }
})

// macOS: re-open when dock icon is clicked — show the companion, not the panel
app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    // Recreate windows; IPC handlers are NOT re-registered (they were registered
    // once at startup with getters that read these mutable refs).
    mainWindow = createMainWindow()
    companionWindow = createCompanionWindow()
    guidanceWindow = createGuidanceWindow(companionWindow)
    voicePlayerWindow = createVoicePlayerWindow()
  } else {
    showCompanion()
  }
})

// Safety net: if all windows close for any reason, quit
app.on('window-all-closed', () => {
  stopAnalysisLoop()
  app.quit()
})

// Safety net: clean up on quit signal (Cmd+Q, etc.)
app.on('before-quit', () => {
  stopAnalysisLoop()
})
